# Generated by Django 2.1.4 on 2019-02-22 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sukien', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 22, 15, 55, 5, 482538)),
        ),
    ]
